development:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: site_creator_development
  pool: 5
  username: root 
  password: 

test:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: site_creator_test
  pool: 5
  username: root
  password: 

production:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: site_creator_production
  pool: 5
  username: root
  password: 